/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */

import { Contract, Signer, utils } from "ethers";
import { Provider } from "@ethersproject/providers";
import type { IAaveV2Proxy, IAaveV2ProxyInterface } from "../IAaveV2Proxy";

const _abi = [
  {
    inputs: [
      {
        internalType: "address",
        name: "_logic",
        type: "address",
      },
      {
        internalType: "bytes",
        name: "_data",
        type: "bytes",
      },
    ],
    name: "initialize",
    outputs: [],
    stateMutability: "payable",
    type: "function",
  },
];

export class IAaveV2Proxy__factory {
  static readonly abi = _abi;
  static createInterface(): IAaveV2ProxyInterface {
    return new utils.Interface(_abi) as IAaveV2ProxyInterface;
  }
  static connect(
    address: string,
    signerOrProvider: Signer | Provider
  ): IAaveV2Proxy {
    return new Contract(address, _abi, signerOrProvider) as IAaveV2Proxy;
  }
}
