/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */

import { Contract, Signer, utils } from "ethers";
import { Provider } from "@ethersproject/providers";
import type { IAttacker, IAttackerInterface } from "../IAttacker";

const _abi = [
  {
    inputs: [
      {
        internalType: "contract IERC20",
        name: "token",
        type: "address",
      },
      {
        internalType: "address",
        name: "sender",
        type: "address",
      },
    ],
    name: "attack",
    outputs: [],
    stateMutability: "payable",
    type: "function",
  },
  {
    inputs: [
      {
        internalType: "contract IERC20",
        name: "",
        type: "address",
      },
      {
        internalType: "address",
        name: "",
        type: "address",
      },
    ],
    name: "attackDelegated",
    outputs: [],
    stateMutability: "payable",
    type: "function",
  },
  {
    inputs: [],
    name: "setup",
    outputs: [],
    stateMutability: "payable",
    type: "function",
  },
];

export class IAttacker__factory {
  static readonly abi = _abi;
  static createInterface(): IAttackerInterface {
    return new utils.Interface(_abi) as IAttackerInterface;
  }
  static connect(
    address: string,
    signerOrProvider: Signer | Provider
  ): IAttacker {
    return new Contract(address, _abi, signerOrProvider) as IAttacker;
  }
}
