/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */

import { ethers } from "ethers";
import {
  FactoryOptions,
  HardhatEthersHelpers as HardhatEthersHelpersBase,
} from "@nomiclabs/hardhat-ethers/types";

import * as Contracts from ".";

declare module "hardhat/types/runtime" {
  interface HardhatEthersHelpers extends HardhatEthersHelpersBase {
    getContractFactory(
      name: "Attacker",
      signerOrOptions?: ethers.Signer | FactoryOptions
    ): Promise<Contracts.Attacker__factory>;
    getContractFactory(
      name: "IAaveV2Proxy",
      signerOrOptions?: ethers.Signer | FactoryOptions
    ): Promise<Contracts.IAaveV2Proxy__factory>;
    getContractFactory(
      name: "IAttacker",
      signerOrOptions?: ethers.Signer | FactoryOptions
    ): Promise<Contracts.IAttacker__factory>;
    getContractFactory(
      name: "IProxy",
      signerOrOptions?: ethers.Signer | FactoryOptions
    ): Promise<Contracts.IProxy__factory>;
    getContractFactory(
      name: "IRegistry",
      signerOrOptions?: ethers.Signer | FactoryOptions
    ): Promise<Contracts.IRegistry__factory>;
    getContractFactory(
      name: "IERC20",
      signerOrOptions?: ethers.Signer | FactoryOptions
    ): Promise<Contracts.IERC20__factory>;

    getContractAt(
      name: "Attacker",
      address: string,
      signer?: ethers.Signer
    ): Promise<Contracts.Attacker>;
    getContractAt(
      name: "IAaveV2Proxy",
      address: string,
      signer?: ethers.Signer
    ): Promise<Contracts.IAaveV2Proxy>;
    getContractAt(
      name: "IAttacker",
      address: string,
      signer?: ethers.Signer
    ): Promise<Contracts.IAttacker>;
    getContractAt(
      name: "IProxy",
      address: string,
      signer?: ethers.Signer
    ): Promise<Contracts.IProxy>;
    getContractAt(
      name: "IRegistry",
      address: string,
      signer?: ethers.Signer
    ): Promise<Contracts.IRegistry>;
    getContractAt(
      name: "IERC20",
      address: string,
      signer?: ethers.Signer
    ): Promise<Contracts.IERC20>;

    // default types
    getContractFactory(
      name: string,
      signerOrOptions?: ethers.Signer | FactoryOptions
    ): Promise<ethers.ContractFactory>;
    getContractFactory(
      abi: any[],
      bytecode: ethers.utils.BytesLike,
      signer?: ethers.Signer
    ): Promise<ethers.ContractFactory>;
    getContractAt(
      nameOrAbi: string | any[],
      address: string,
      signer?: ethers.Signer
    ): Promise<ethers.Contract>;
  }
}
